#!/bin/bash
# make-shortcut.sh — build a double-clickable "Cities Skylines II.app" launcher in ~/Applications,
# with the game's own icon extracted from your installed Cities2.exe.
#
# Why a script: the .app is three generated files (Info.plist, a launch shim, an .icns). Hand-making
# it is fiddly, and the icon has to come from YOUR game install — this repo does not (and must not)
# redistribute Paradox artwork, so the icon is extracted locally at build time from the copy you own.
#
# Usage:
#   bash scripts/make-shortcut.sh                    # default stack (Wine 11 + DXMT)
#   bash scripts/make-shortcut.sh --stack d3dmetal   # Wine 10 + D3DMetal fallback
#   bash scripts/make-shortcut.sh --dest /tmp/try    # build somewhere else (testing)
#   bash scripts/make-shortcut.sh --launcher ~/path/to/launch.sh --game "/path/to/Cities2.exe"
#
# Safe to re-run: it replaces its own bundle and nothing else. Requires python3 only for the icon
# (Xcode Command Line Tools ships it); without it the bundle still builds, just with a generic icon.
set -u

STACK="dxmt11"
DEST="$HOME/Applications"
APPNAME="Cities Skylines II"
LAUNCHER=""
GAME_EXE=""

while [ $# -gt 0 ]; do
  case "$1" in
    --stack)    STACK="${2:-}"; shift 2 ;;
    --dest)     DEST="${2:-}"; shift 2 ;;
    --name)     APPNAME="${2:-}"; shift 2 ;;
    --launcher) LAUNCHER="${2:-}"; shift 2 ;;
    --game)     GAME_EXE="${2:-}"; shift 2 ;;
    -h|--help)  sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $1 (try --help)"; exit 2 ;;
  esac
done

case "$STACK" in
  dxmt11|wine11) DEFAULT_LAUNCHER="$HOME/cs2-patch/launch-cs2-dxmt11.sh"
                 DEFAULT_WRAPPER="$HOME/Applications/CS2dxmt11.app" ;;
  d3dmetal|wine10) DEFAULT_LAUNCHER="$HOME/cs2-patch/launch-cs2.sh"
                 DEFAULT_WRAPPER="$HOME/Applications/S734M.app" ;;
  *) echo "unknown --stack '$STACK' (use dxmt11 or d3dmetal)"; exit 2 ;;
esac
[ -n "$LAUNCHER" ] || LAUNCHER="$DEFAULT_LAUNCHER"
[ -n "$GAME_EXE" ] || GAME_EXE="$DEFAULT_WRAPPER/Contents/SharedSupport/prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Cities Skylines II/Cities2.exe"

APP="$DEST/$APPNAME.app"
echo "=== building $APP ==="
echo "    stack:    $STACK"
echo "    launcher: $LAUNCHER"

if [ ! -f "$LAUNCHER" ]; then
  echo
  echo "!! Launcher not found: $LAUNCHER"
  echo "   The .app is only a shim — it needs the real launcher script to exist first."
  echo "   Point at it with --launcher <path>, or see INSTALL.md for how to set one up."
  exit 1
fi

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ---------------------------------------------------------------- launch shim
# Quiet by design: milestones become macOS notifications, failures become alert dialogs, and a
# double-click never leaves a Terminal window sitting on "[Process completed]".
cat > "$APP/Contents/MacOS/launch" << SHIM
#!/bin/bash
# Generated by scripts/make-shortcut.sh — re-run that instead of editing this file.
SCRIPT="$LAUNCHER"
LOG="\$HOME/Library/Logs/cs2-launcher.log"
mkdir -p "\$(dirname "\$LOG")"

if [ ! -f "\$SCRIPT" ]; then
  osascript -e 'display alert "Cities: Skylines II" message "Launcher script is missing. Re-run scripts/make-shortcut.sh." as critical'
  exit 1
fi
if pgrep -f 'Cities2.exe' >/dev/null 2>&1; then
  osascript -e 'display notification "Already running." with title "Cities: Skylines II"'
  exit 0
fi

chmod +x "\$SCRIPT" 2>/dev/null
{ echo; echo "===== \$(date '+%Y-%m-%d %H:%M:%S') ====="; } >> "\$LOG"
CS2_QUIET=1 bash "\$SCRIPT" >> "\$LOG" 2>&1
rc=\$?
if [ \$rc -ne 0 ]; then
  osascript -e "display alert \"Cities: Skylines II\" message \"Launch failed (exit \$rc). Open the log?\" buttons {\"Dismiss\",\"Open Log\"} default button \"Open Log\"" \\
    -e 'if button returned of result is "Open Log" then do shell script "open ~/Library/Logs/cs2-launcher.log"' >/dev/null 2>&1
fi
exit \$rc
SHIM
chmod +x "$APP/Contents/MacOS/launch"

# ---------------------------------------------------------------- icon (local extraction)
ICON_OK=0
if [ -f "$GAME_EXE" ] && command -v python3 >/dev/null 2>&1; then
  TMP=$(mktemp -d)
  if python3 - "$GAME_EXE" "$TMP/icon" << 'PY'
# Pull the largest RT_ICON out of a PE binary. Pure stdlib: no pefile, no icoutils.
import struct, sys
src, out = sys.argv[1], sys.argv[2]
d = open(src, 'rb').read()

pe = struct.unpack_from('<I', d, 0x3c)[0]
if d[pe:pe+4] != b'PE\0\0': sys.exit('not a PE')
nsec, optsz = struct.unpack_from('<HH', d, pe + 6), None
nsec = struct.unpack_from('<H', d, pe + 6)[0]
optsz = struct.unpack_from('<H', d, pe + 20)[0]
opt = pe + 24
magic = struct.unpack_from('<H', d, opt)[0]
ddoff = opt + (112 if magic == 0x20b else 96)          # PE32+ vs PE32
res_rva, res_size = struct.unpack_from('<II', d, ddoff + 2 * 8)   # DataDirectory[2] = resources
if not res_rva: sys.exit('no resource directory')

sections = []
sh = opt + optsz
for i in range(nsec):
    o = sh + i * 40
    # section header: Name[8] VirtualSize@8 VirtualAddress@12 SizeOfRawData@16 PointerToRawData@20
    vsz = struct.unpack_from('<I', d, o + 8)[0]
    va, rawsz, rawptr = struct.unpack_from('<III', d, o + 12)
    sections.append((va, max(vsz, rawsz), rawptr))

def to_off(rva):
    for va, sz, ptr in sections:
        if va <= rva < va + sz:
            return ptr + (rva - va)
    return None

base = to_off(res_rva)

def entries(off):
    nnamed, nid = struct.unpack_from('<HH', d, off + 12)
    for i in range(nnamed + nid):
        eid, child = struct.unpack_from('<II', d, off + 16 + i * 8)
        yield eid, child

best = None
for eid, child in entries(base):                       # level 1: resource type
    if (eid & 0x7fffffff) != 3 or not (child & 0x80000000):   # RT_ICON == 3
        continue
    for _, c2 in entries(base + (child & 0x7fffffff)):  # level 2: icon id
        if not (c2 & 0x80000000):
            continue
        for _, c3 in entries(base + (c2 & 0x7fffffff)):  # level 3: language
            if c3 & 0x80000000:
                continue
            drva, dsz = struct.unpack_from('<II', d, base + c3)
            o = to_off(drva)
            if o and (best is None or dsz > best[1]):
                best = (o, dsz)

if not best: sys.exit('no RT_ICON found')
off, size = best
blob = d[off:off + size]

if blob[:8] == b'\x89PNG\r\n\x1a\n':                   # modern icons embed PNG directly
    open(out + '.png', 'wb').write(blob)
    print('png')
else:                                                   # legacy DIB — wrap as a one-image .ico
    w = struct.unpack_from('<i', blob, 4)[0]
    h = struct.unpack_from('<i', blob, 8)[0] // 2
    hdr = struct.pack('<HHH', 0, 1, 1) + struct.pack('<BBBBHHII',
        w if w < 256 else 0, h if h < 256 else 0, 0, 0, 1, 32, len(blob), 22)
    open(out + '.ico', 'wb').write(hdr + blob)
    print('ico')
PY
  then
    SRC=""
    [ -f "$TMP/icon.png" ] && SRC="$TMP/icon.png"
    [ -z "$SRC" ] && [ -f "$TMP/icon.ico" ] && sips -s format png "$TMP/icon.ico" --out "$TMP/icon.png" >/dev/null 2>&1 && SRC="$TMP/icon.png"
    if [ -n "$SRC" ]; then
      ISET="$TMP/cs2.iconset"; mkdir -p "$ISET"
      for sz in 16 32 128 256 512; do
        sips -z $sz $sz          "$SRC" --out "$ISET/icon_${sz}x${sz}.png"    >/dev/null 2>&1
        sips -z $((sz*2)) $((sz*2)) "$SRC" --out "$ISET/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1
      done
      if iconutil -c icns "$ISET" -o "$APP/Contents/Resources/cs2.icns" >/dev/null 2>&1; then
        ICON_OK=1
        echo "    icon:     extracted from Cities2.exe ($(sips -g pixelWidth "$SRC" 2>/dev/null | awk '/pixelWidth/{print $2}')px source)"
      fi
    fi
  fi
  rm -rf "$TMP"
fi
[ "$ICON_OK" = 1 ] || echo "    icon:     skipped (generic icon) — game exe or python3 not found; the app still works"

# ---------------------------------------------------------------- Info.plist
cat > "$APP/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>$APPNAME</string>
    <key>CFBundleDisplayName</key>     <string>Cities: Skylines II</string>
    <key>CFBundleIdentifier</key>      <string>local.cs2.$STACK.launcher</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>launch</string>$([ "$ICON_OK" = 1 ] && printf '\n    <key>CFBundleIconFile</key>        <string>cs2.icns</string>')
    <key>LSMinimumSystemVersion</key>  <string>13.0</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

touch "$APP"                       # nudge Finder to pick up the new icon
echo "=== done ==="
echo "Double-click: $APP"
echo "Log:          ~/Library/Logs/cs2-launcher.log"
