#!/bin/bash
# make-steam-shortcut.sh — build a double-clickable "CS2 Steam Store.app" that opens Steam's
# VISIBLE window in the storefront wrapper (wine 11.0), with Steam's own icon.
#
# Why it exists: the self-built 11.16 engine is the play wrapper, but Steam's visible storefront
# is black on it (embedded Chromium never rendered on stock Wine here — GOTCHAS, dxmt#141). The
# Porting Kit 11.0 engine renders the store fine, and Steam licences are account-level, so the
# split costs nothing: play in the 11.16 wrapper, shop in the 11.0 one. This app is the "shop"
# double-click; the existing "Cities Skylines II.app" stays the "play" one.
#
# If the storefront wrapper doesn't exist yet, this script CREATES it from the daily wrapper:
#   1. `cp -c` APFS clone — instant, shares disk (GOTCHAS § "du lies about disk on APFS")
#   2. restores the original 11.0 engine inside the clone from the wine.pk11.0-BAK that
#      build-engine-1116.sh leaves behind (the clone must NOT run 11.16 — black storefront)
#   3. removes the game install from the clone — tree AND appmanifest together, so its Steam
#      neither re-downloads nor tries to update a second copy (the store wrapper only needs
#      Steam itself; game licences don't care which wrapper bought them)
#
# Usage:
#   bash scripts/make-steam-shortcut.sh                  # default paths, creates wrapper if needed
#   --wrapper /path/Store.app      storefront wrapper (default ~/Applications/CS2dxmt11-pk110.app)
#   --from /path/Daily.app         clone donor when creating (default ~/Applications/CS2dxmt11.app)
#   --name "CS2 Steam Store"       app name        --dest ~/Applications
#
# Safe to re-run: replaces its own .app bundle and nothing else; skips the clone if the
# storefront wrapper already exists.
set -u

DEST="$HOME/Applications"
APPNAME="CS2 Steam Store"
WRAPPER="$HOME/Applications/CS2dxmt11-pk110.app"
DONOR="$HOME/Applications/CS2dxmt11.app"

while [ $# -gt 0 ]; do
  case "$1" in
    --wrapper) WRAPPER="${2:-}"; shift 2 ;;
    --from)    DONOR="${2:-}"; shift 2 ;;
    --dest)    DEST="${2:-}"; shift 2 ;;
    --name)    APPNAME="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,27p' "$0"; exit 0 ;;
    *) echo "unknown option: $1 (try --help)"; exit 2 ;;
  esac
done

SS="$WRAPPER/Contents/SharedSupport"
APPID=949230   # Cities: Skylines II (appmanifest_228980 = Steamworks redistributables — leave it; its files stay)

# ------------------------------------------------- create the storefront wrapper if missing
if [ ! -d "$SS/prefix" ]; then
  DSS="$DONOR/Contents/SharedSupport"
  [ -d "$DSS/prefix" ] || { echo "ERROR: no storefront wrapper at $WRAPPER and no donor at $DONOR — install the base stack first (INSTALL.md), or pass --from"; exit 1; }
  # refuse to clone out from under a live Steam — cmdline pgrep misses Windows-argv steam, so
  # attribute by open files against the donor prefix (measured 2026-08-24)
  for _p in $(pgrep -f "steam" 2>/dev/null); do
    lsof -p "$_p" 2>/dev/null | grep -q "$DSS/prefix" && \
      { echo "ERROR: Steam is running in $(basename "$DONOR") — quit it first (steam.exe -shutdown; never kill -9)."; exit 1; }
  done
  echo "Storefront wrapper not found — creating it from $(basename "$DONOR") (APFS clone, seconds, ~no extra disk):"
  cp -Rc "$DONOR" "$WRAPPER" || { echo "ERROR: clone failed (same APFS volume required)"; rm -rf "$WRAPPER"; exit 1; }
  if [ -d "$SS/wine.pk11.0-BAK" ]; then
    # donor was already engine-swapped to 11.16 — put the original 11.0 engine back IN THE CLONE
    rm -rf "$SS/wine"
    mv "$SS/wine.pk11.0-BAK" "$SS/wine"
    echo "  engine: restored wine 11.0 inside the clone (from wine.pk11.0-BAK)"
  fi
  GDIR_CLONE="$SS/prefix/drive_c/Program Files (x86)/Steam/steamapps"
  rm -rf "$GDIR_CLONE/common/Cities Skylines II"
  rm -f  "$GDIR_CLONE/appmanifest_$APPID.acf"
  echo "  game:   removed from the clone (tree + appmanifest together — Steam won't re-fetch)"
fi

# ------------------------------------------------- preflight
WINE64="$SS/wine/bin/wine64"
STEAM_EXE="$SS/prefix/drive_c/Program Files (x86)/Steam/steam.exe"
[ -x "$WINE64" ]    || { echo "ERROR: no wine64 inside $(basename "$WRAPPER") — wrapper looks incomplete"; exit 1; }
[ -f "$STEAM_EXE" ] || { echo "ERROR: Steam is not installed inside $(basename "$WRAPPER") (INSTALL.md step 2)"; exit 1; }
WV="$("$WINE64" --version 2>/dev/null)"
case "$WV" in
  *11.16*) echo "WARNING: this wrapper runs $WV — Steam's storefront is known BLACK on the 11.16 engine (that's the whole reason for the wrapper split). Point --wrapper at a wine 11.0 wrapper." ;;
esac

APP="$DEST/$APPNAME.app"
echo "=== building $APP ==="
echo "    wrapper: $WRAPPER ($WV)"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# ------------------------------------------------- launch shim
cat > "$APP/Contents/MacOS/launch" << SHIM
#!/bin/bash
# Generated by scripts/make-steam-shortcut.sh — re-run that instead of editing this file.
WRAPPER="$WRAPPER"
SHIM
cat >> "$APP/Contents/MacOS/launch" << 'SHIM'
SS="$WRAPPER/Contents/SharedSupport"
STEAM="$SS/prefix/drive_c/Program Files (x86)/Steam/steam.exe"
if [ ! -x "$SS/wine/bin/wine64" ] || [ ! -f "$STEAM" ]; then
  osascript -e 'display alert "CS2 Steam Store" message "Storefront wrapper is missing or incomplete. Re-run scripts/make-steam-shortcut.sh from the repo." as critical' >/dev/null 2>&1
  exit 1
fi
export WINEPREFIX="$SS/prefix"
export PATH="$SS/wine/bin:$PATH"
export DYLD_FALLBACK_LIBRARY_PATH="$WRAPPER/Contents/Frameworks:$SS/wine/lib:/usr/lib:/usr/local/lib"
export WINEDEBUG=-all
export WINEDLLOVERRIDES="gameoverlayrenderer64=d;gameoverlayrenderer=d;winemenubuilder.exe=d"

# Is Steam already up IN THIS PREFIX? Attribute by open files, not by command line: a steam.exe
# re-exec'd by its own updater carries a Windows-style argv no path-pgrep can see, and webhelper
# children always do (measured 2026-08-24).
running=""
for p in $(pgrep -f "steam.exe" 2>/dev/null); do
  case "$(ps -o command= -p "$p" 2>/dev/null)" in *steamwebhelper*) continue ;; esac
  lsof -p "$p" 2>/dev/null | grep -q "$SS/prefix" && { running=$p; break; }
done

if [ -n "$running" ]; then
  # Forward an open-main to the running instance — Steam raises its own window.
  nohup "$SS/wine/bin/wine64" "$STEAM" "steam://open/main" >/dev/null 2>&1 &
  osascript -e 'display notification "Steam is already running — bringing up its window." with title "CS2 Steam Store"' >/dev/null 2>&1
else
  # a stale 0-byte .crash marker makes steam.exe exit 1 and never start — clear it first
  rm -f "$WINEPREFIX/drive_c/Program Files (x86)/Steam/.crash" 2>/dev/null
  nohup "$SS/wine/bin/wine64" "$STEAM" -no-cef-sandbox >/dev/null 2>&1 &
  osascript -e 'display notification "Starting Steam in the storefront wrapper — window takes ~20 s." with title "CS2 Steam Store"' >/dev/null 2>&1
fi
exit 0
SHIM
chmod +x "$APP/Contents/MacOS/launch"

# ------------------------------------------------- icon (Steam's own, extracted locally)
ICON_OK=0
if command -v python3 >/dev/null 2>&1; then
  TMP=$(mktemp -d)
  if python3 "$(cd "$(dirname "$0")" && pwd)/pe-icon.py" "$STEAM_EXE" "$TMP/icon" >/dev/null 2>&1; then
    SRC=""
    [ -f "$TMP/icon.png" ] && SRC="$TMP/icon.png"
    [ -z "$SRC" ] && [ -f "$TMP/icon.ico" ] && sips -s format png "$TMP/icon.ico" --out "$TMP/icon.png" >/dev/null 2>&1 && SRC="$TMP/icon.png"
    if [ -n "$SRC" ]; then
      ISET="$TMP/steam.iconset"; mkdir -p "$ISET"
      for sz in 16 32 128 256 512; do
        sips -z $sz $sz          "$SRC" --out "$ISET/icon_${sz}x${sz}.png"    >/dev/null 2>&1
        sips -z $((sz*2)) $((sz*2)) "$SRC" --out "$ISET/icon_${sz}x${sz}@2x.png" >/dev/null 2>&1
      done
      iconutil -c icns "$ISET" -o "$APP/Contents/Resources/steamstore.icns" >/dev/null 2>&1 && ICON_OK=1 \
        && echo "    icon:    extracted from steam.exe"
    fi
  fi
  rm -rf "$TMP"
fi
[ "$ICON_OK" = 1 ] || echo "    icon:    skipped (generic) — python3 missing or extraction failed; the app still works"

# ------------------------------------------------- Info.plist
cat > "$APP/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>$APPNAME</string>
    <key>CFBundleDisplayName</key>     <string>$APPNAME</string>
    <key>CFBundleIdentifier</key>      <string>local.cs2.steamstore</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>launch</string>$([ "$ICON_OK" = 1 ] && printf '\n    <key>CFBundleIconFile</key>        <string>steamstore.icns</string>')
    <key>LSMinimumSystemVersion</key>  <string>13.0</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

touch "$APP"
echo "=== done ==="
echo "Shop:  double-click  $APP   (storefront, wine 11.0 wrapper)"
echo "Play:  double-click  ~/Applications/Cities Skylines II.app   (game, 11.16 wrapper)"
echo "Licences are account-level — a purchase in one wrapper is immediately usable in the other."
