#!/bin/bash
# regen-winemac-patches.sh — generate the three published winemac.drv patches from git.
#
#   bash scripts/regen-winemac-patches.sh --check     # drift gate: regenerate to a temp dir and
#                                                     # cmp against scripts/*.patch (exit 1 on drift)
#   bash scripts/regen-winemac-patches.sh --install   # write them into scripts/
#   bash scripts/regen-winemac-patches.sh --out DIR   # write them somewhere else
#
# WHY: a hand-maintained patch drifts from the binary it claims to describe. The published combined
# patch grew as prose — six dated addenda — while the real code lived in the build tree, could not
# be applied, and was linked from wine bug 60263 as "a working version" (GOTCHAS 2026-09-02). The
# source is now a git repo and every patch is generated; --check is the `button up` gate that keeps
# it that way. Plan: docs/plans/winemac-reference-upstream-form.md § 1 and § 3.
#
# THE HISTORY THIS READS (branches in the nested repo):
#   stock     pristine wine 11.16 winemac.drv, byte-identical to build-1116/wine-11.16/
#   aquadran  stock + scripts/wineandaqua-dxmt.patch (aquadran's DXMT support; not this project's)
#   core      branched off STOCK — the stock-applicable half, insertion points deliberately placed
#             away from aquadran's so `git diff stock core` applies to stock AND stock+aquadran
#   main      aquadran -> cherry-pick(core) -> glue
set -u
REPO="${WINEMAC_SRC:-$HOME/cs2-patch/build-1116/wine-11.16-dxmt/dlls/winemac.drv}"
HERE="$(cd "$(dirname "$0")" && pwd)"
MODE=out; OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE=check ;;
    --install) MODE=install; OUT="$HERE" ;;
    --out) shift; MODE=out; OUT="${1:-}" ;;
    *) echo "unknown arg: $1" >&2; exit 64 ;;
  esac
  shift
done
[ -d "$REPO/.git" ] || { echo "ERROR: no git repo at $REPO (set WINEMAC_SRC)" >&2; exit 64; }
for b in stock aquadran core main; do
  git -C "$REPO" rev-parse --verify -q "$b" >/dev/null || { echo "ERROR: branch '$b' missing in $REPO" >&2; exit 64; }
done
[ -n "$OUT" ] || OUT="$(mktemp -d /tmp/winemac-patches.XXXXXX)"
mkdir -p "$OUT"

# The header every published patch carries. $1 = title line, $2 = the APPLY paragraph.
common_header() {
cat <<HDR
# $1
#
# WARNING: AI-AUTHORED. Read this before you read the code.
#
# This patch was written with heavy AI assistance. 3Shain/dxmt's CONTRIBUTING.md cannot accept
# AI-authored contributions, so it was never offered as a PR; the findings went upstream as reports
# instead: https://github.com/3Shain/dxmt/issues/141#issuecomment-5477055980 and
# https://bugs.winehq.org/show_bug.cgi?id=60263. It is published here on purpose. If you are a wine
# or dxmt maintainer who intends to write your own implementation, reading this file is a choice
# with a consequence: the reports carry the whole diagnosis with none of the code.
#
# LICENSING. The five files this touches are LGPL-2.1-or-later with CodeWeavers copyright lines,
# and a unified diff of them reproduces LGPL context and removed lines. The modifications are
# (c) 2026 the author and are offered under LGPL-2.1-or-later, the license of the files they
# modify; context lines are Wine's and are not relicensed. This repository's own scripts and docs
# remain MIT.
#
$2#
# Generated by scripts/regen-winemac-patches.sh — do not hand-edit; regenerate.
HDR
}

gen() { # gen <file> <git-diff-range> <title> <apply-paragraph>
  local f="$OUT/$1" range="$2"
  common_header "$3" "$4" > "$f"
  git -C "$REPO" diff "$range" >> "$f"
  printf '  %-46s %6s lines\n' "$1" "$(wc -l < "$f" | tr -d ' ')"
}

APPLY_COMBINED='# APPLY: to a wine 11.16 tree that already carries scripts/wineandaqua-dxmt.patch (aquadran'"'"'s
# DXMT support), from the tree root:  patch -p1 < winemac-crossprocess-remote-layer.patch
# Requires wine >= 11.11 (the CAContext/CALayerHost route this builds on landed there).
# Rebuild just the module:  gmake dlls/winemac.drv/winemac.so
# Pairs with scripts/dxmt-remote-layer-fallback.patch; NEITHER half works alone.
# This file is the two halves below combined, and is what wine bug 60263 links:
#   scripts/winemac-crossprocess-child-core.patch  — stock-applicable, no DXMT dependency
#   scripts/winemac-crossprocess-dxmt-glue.patch   — the DXMT-specific layer on top
'
APPLY_CORE='# APPLY: to a PRISTINE wine 11.16 tree, from the tree root:
#   patch -p1 < winemac-crossprocess-child-core.patch
# It also applies cleanly on top of scripts/wineandaqua-dxmt.patch — the insertion points are
# deliberately placed away from that patch'"'"'s. Requires wine >= 11.11.
# This half implements the FIXME for every caller, including vulkan.c, and depends on nothing
# from DXMT. On its own it changes no behaviour for an application that never asks for a
# cross-process child swapchain.
'
APPLY_GLUE='# APPLY: on top of core + scripts/wineandaqua-dxmt.patch, from the tree root:
#   patch -p1 < winemac-crossprocess-dxmt-glue.patch
# DXMT-specific: the two dlsym-reachable exports, the view-keyed surface table with its per-child
# deferred release, and the deferred layer background. Pairs with
# scripts/dxmt-remote-layer-fallback.patch; NEITHER half works alone.
'

echo "regenerating from $REPO"
gen winemac-crossprocess-remote-layer.patch  aquadran..main \
    'winemac-crossprocess-remote-layer.patch — the wine half of the cross-process Steam fix (combined).' \
    "$APPLY_COMBINED"
gen winemac-crossprocess-child-core.patch    stock..core \
    'winemac-crossprocess-child-core.patch — cross-process child window Metal swapchains (stock wine).' \
    "$APPLY_CORE"
gen winemac-crossprocess-dxmt-glue.patch     core-merge..main \
    'winemac-crossprocess-dxmt-glue.patch — the DXMT-specific layer over the core patch.' \
    "$APPLY_GLUE"

if [ "$MODE" = check ]; then
  rc=0
  for f in winemac-crossprocess-remote-layer.patch winemac-crossprocess-child-core.patch winemac-crossprocess-dxmt-glue.patch; do
    if cmp -s "$OUT/$f" "$HERE/$f"; then echo "  ok    $f"
    else echo "  DRIFT $f — the committed copy differs from git; regenerate with --install"; rc=1; fi
  done
  exit $rc
fi
echo "written to $OUT"
