#!/bin/bash
# regen-winemac-patches.sh — generate the three published winemac.drv patches from git.
#
#   bash scripts/regen-winemac-patches.sh --check     # drift gate: regenerate to a temp dir and
#                                                     # cmp against scripts/*.patch (exit 1 on drift)
#   bash scripts/regen-winemac-patches.sh --install   # write them into scripts/
#   bash scripts/regen-winemac-patches.sh --out DIR   # write them somewhere else
#
# WHY: a hand-maintained patch drifts from the binary it claims to describe. The published combined
# patch grew as prose — six dated addenda — while the real code lived in the build tree, could not
# be applied, and was linked from wine bug 60263 as "a working version" (GOTCHAS 2026-09-02). The
# source is now a git repo and every patch is generated; --check is the `button up` gate that keeps
# it that way. Plan: docs/plans/winemac-reference-upstream-form.md § 1 and § 3.
#
# THE HISTORY THIS READS (branches in the nested repo):
#   stock     pristine wine 11.16 winemac.drv, byte-identical to build-1116/wine-11.16/
#   aquadran  stock + scripts/wineandaqua-dxmt.patch (aquadran's DXMT support; not this project's)
#   core      branched off STOCK — the stock-applicable half, insertion points deliberately placed
#             away from aquadran's so `git diff stock core` applies to stock AND stock+aquadran
#   main      aquadran -> cherry-pick(core) -> glue
set -u
REPO="${WINEMAC_SRC:-$HOME/cs2-patch/build-1116/wine-11.16-dxmt/dlls/winemac.drv}"
HERE="$(cd "$(dirname "$0")" && pwd)"
MODE=out; OUT=""
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE=check ;;
    --install) MODE=install; OUT="$HERE" ;;
    --out) shift; MODE=out; OUT="${1:-}" ;;
    *) echo "unknown arg: $1" >&2; exit 64 ;;
  esac
  shift
done
[ -d "$REPO/.git" ] || { echo "ERROR: no git repo at $REPO (set WINEMAC_SRC)" >&2; exit 64; }
for b in stock aquadran core main; do
  git -C "$REPO" rev-parse --verify -q "$b" >/dev/null || { echo "ERROR: branch '$b' missing in $REPO" >&2; exit 64; }
done
[ -n "$OUT" ] || OUT="$(mktemp -d /tmp/winemac-patches.XXXXXX)"
mkdir -p "$OUT"

# The header every published patch carries. $1 = title line, $2 = the APPLY paragraph, $3 = the
# number of files the diff touches (counted, not typed: the core header said "five" for a
# four-file diff until 2026-09-03).
words() { case "$1" in 1) echo one;; 2) echo two;; 3) echo three;; 4) echo four;; 5) echo five;; 6) echo six;; *) echo "$1";; esac; }
common_header() {
cat <<HDR
# $1
#
# WARNING: AI-AUTHORED. Read this before you read the code.
#
# This patch was written with heavy AI assistance. 3Shain/dxmt's CONTRIBUTING.md cannot accept
# AI-authored contributions, so it was never offered as a PR; the findings went upstream as reports
# instead: https://github.com/3Shain/dxmt/issues/141#issuecomment-5477055980 and
# https://bugs.winehq.org/show_bug.cgi?id=60263. It is published here on purpose. If you are a wine
# or dxmt maintainer who intends to write your own implementation, reading this file is a choice
# with a consequence: the reports carry the whole diagnosis with none of the code.
#
# LICENSING. The $(words "$3") files this touches are LGPL-2.1-or-later with CodeWeavers copyright lines,
# and a unified diff of them reproduces LGPL context and removed lines. The modifications are
# (c) 2026 the author and are offered under LGPL-2.1-or-later, the license of the files they
# modify; context lines are Wine's and are not relicensed. This repository's own scripts and docs
# remain MIT.
#
$2#
# Generated by scripts/regen-winemac-patches.sh — do not hand-edit; regenerate.
HDR
}

gen() { # gen <file> <git-diff-range> <title> <apply-paragraph>
  local f="$OUT/$1" range="$2" n
  n="$(git -C "$REPO" diff --name-only "$range" | wc -l | tr -d ' ')"
  common_header "$3" "$4" "$n" > "$f"
  git -C "$REPO" diff "$range" >> "$f"
  printf '  %-46s %6s lines\n' "$1" "$(wc -l < "$f" | tr -d ' ')"
}

APPLY_COMBINED='# APPLY: to a wine 11.16 tree that already carries scripts/wineandaqua-dxmt.patch (aquadran'"'"'s
# DXMT support), from the tree root:  patch -p1 < winemac-crossprocess-remote-layer.patch
# Requires wine >= 11.11 (the CAContext/CALayerHost route this builds on landed there).
# Rebuild just the module:  gmake dlls/winemac.drv/winemac.so
# Pairs with scripts/dxmt-remote-layer-fallback.patch; NEITHER half works alone.
# This file is the two halves below combined, and is what wine bug 60263 links:
#   scripts/winemac-crossprocess-child-core.patch  — stock-applicable, no DXMT dependency
#   scripts/winemac-crossprocess-dxmt-glue.patch   — the DXMT-specific layer on top
'
APPLY_CORE='# APPLY: to a PRISTINE wine 11.16 tree, from the tree root:
#   patch -p1 < winemac-crossprocess-child-core.patch
# It also applies cleanly on top of scripts/wineandaqua-dxmt.patch — the insertion points are
# deliberately placed away from that patch'"'"'s. Requires wine >= 11.11.
# This half implements the FIXME for every caller, including vulkan.c, and depends on nothing
# from DXMT. On its own it changes no behaviour for an application that never asks for a
# cross-process child swapchain.
'
APPLY_GLUE='# APPLY: on top of core + scripts/wineandaqua-dxmt.patch, from the tree root:
#   patch -p1 < winemac-crossprocess-dxmt-glue.patch
# DXMT-specific: the two dlsym-reachable exports, the view-keyed surface table with its per-child
# deferred release, and the deferred layer background. Pairs with
# scripts/dxmt-remote-layer-fallback.patch; NEITHER half works alone.
'

# Glue is pinned by its commit SUBJECT, not by position, and main's tip must BE that commit.
# `main~1..main` silently produced the wrong diff the day two more commits landed on main
# (2026-09-03): the combined patch grew, the "glue" became the newest commit's diff, and the
# committed core patch quietly lacked the fixes in the installed module. Commits that belong on
# main after glue do not exist: stock-applicable work goes on core, main is rebuilt on top.
GLUE="$(git -C "$REPO" log --format=%H --grep='^winemac: DXMT glue over' main)"
[ "$(printf '%s\n' "$GLUE" | grep -c .)" = 1 ] || { echo "ERROR: expected exactly one glue commit on main, found: $GLUE" >&2; exit 65; }
[ "$(git -C "$REPO" rev-parse main)" = "$GLUE" ] || { echo "ERROR: main's tip is not the glue commit — something landed on main after glue. Cherry-pick it onto core, rebuild main as aquadran -> core -> glue, confirm the tree is unchanged (GOTCHAS 2026-09-03)" >&2; exit 65; }

echo "regenerating from $REPO"
gen winemac-crossprocess-remote-layer.patch  aquadran..main \
    'winemac-crossprocess-remote-layer.patch — the wine half of the cross-process Steam fix (combined).' \
    "$APPLY_COMBINED"
gen winemac-crossprocess-child-core.patch    stock..core \
    'winemac-crossprocess-child-core.patch — cross-process child window Metal swapchains (stock wine).' \
    "$APPLY_CORE"
gen winemac-crossprocess-dxmt-glue.patch     "$GLUE~1..$GLUE" \
    'winemac-crossprocess-dxmt-glue.patch — the DXMT-specific layer over the core patch.' \
    "$APPLY_GLUE"

if [ "$MODE" = check ]; then
  rc=0
  for f in winemac-crossprocess-remote-layer.patch winemac-crossprocess-child-core.patch winemac-crossprocess-dxmt-glue.patch; do
    if cmp -s "$OUT/$f" "$HERE/$f"; then echo "  ok    $f"
    else echo "  DRIFT $f — the committed copy differs from git; regenerate with --install"; rc=1; fi
  done
  # Structural invariants — the split is only real while these hold. Exercised with `git apply`,
  # which allows offsets but no fuzz and never leaves .orig files behind.
  #   1. core applies to PRISTINE stock                    (the stock-applicable claim)
  #   2. aquadran + core == glue's parent, byte for byte   (core lands exactly where main's history says)
  #   3. glue's parent + glue == main                      (so combined == core + glue)
  T=$(mktemp -d /tmp/winemac-inv.XXXXXX)
  tree() { mkdir -p "$T/$1/dlls/winemac.drv"; git -C "$REPO" archive "$2" | tar -x -C "$T/$1/dlls/winemac.drv"; }
  tree stock stock; tree aq aquadran; tree pre "$GLUE~1"; tree main main
  if git -C "$T/stock" apply -p1 "$OUT/winemac-crossprocess-child-core.patch" 2>/dev/null; then echo "  ok    core applies to pristine stock"; else echo "  FAIL  core does not apply to pristine stock"; rc=1; fi
  if git -C "$T/aq" apply -p1 "$OUT/winemac-crossprocess-child-core.patch" 2>/dev/null && diff -r "$T/aq" "$T/pre" >/dev/null; then echo "  ok    aquadran + core == glue's parent"; else echo "  FAIL  aquadran + core != glue's parent"; rc=1; fi
  if git -C "$T/pre" apply -p1 "$OUT/winemac-crossprocess-dxmt-glue.patch" 2>/dev/null && diff -r "$T/pre" "$T/main" >/dev/null; then echo "  ok    glue's parent + glue == main"; else echo "  FAIL  glue's parent + glue != main"; rc=1; fi
  rm -rf "$T"
  exit $rc
fi
echo "written to $OUT"
